import { requireUser } from "@/lib/auth";
import { supabaseServer } from "@/lib/supabase/server";
import { saveProgramme, deleteProgramme, saveCohort, deleteCohort } from "@/app/(admin)/programmes/actions";
export async function ProgrammeManagement() {
 const user = await requireUser(); if (user.role !== "super_admin") return null;
 const { data } = await (await supabaseServer()).from("programmes").select("*,cohorts(*)").order("name");
 return <section><h2>Manage programmes and cohorts</h2><p>Fee changes apply to future imports only. Deleting a cohort clears the cohort on existing participants.</p>
 <form action={saveProgramme} className="card"><h3>New programme</h3><input name="code" placeholder="Code" required/><input name="name" placeholder="Name" required/><input type="number" name="fee" min="0" step="0.01" required/><label><input type="checkbox" name="active" defaultChecked/>Active</label><button className="btn">Create</button></form>
 {(data ?? []).map(p => <details key={p.id} className="card"><summary>{p.name}</summary><form action={saveProgramme}><input type="hidden" name="id" value={p.id}/><input name="code" defaultValue={p.code} required/><input name="name" defaultValue={p.name} required/><input type="number" name="fee" min="0" step="0.01" defaultValue={p.amount_due} required/><label><input type="checkbox" name="active" defaultChecked={p.is_active}/>Active</label><button className="btn">Save programme</button></form><form action={deleteProgramme}><input type="hidden" name="id" value={p.id}/><button className="btn">Delete unused programme</button></form>
 {(p.cohorts ?? []).map((c: { id: string; code: string; name: string; start_date: string | null; end_date: string | null }) => <div key={c.id}><form action={saveCohort}><input type="hidden" name="id" value={c.id}/><input type="hidden" name="programme_id" value={p.id}/><input name="code" defaultValue={c.code} required/><input name="name" defaultValue={c.name} required/><input type="date" name="start" defaultValue={c.start_date ?? ""}/><input type="date" name="end" defaultValue={c.end_date ?? ""}/><button className="btn">Save cohort</button></form><form action={deleteCohort}><input type="hidden" name="id" value={c.id}/><button className="btn">Delete cohort</button></form></div>)}
 <form action={saveCohort}><h3>New cohort</h3><input type="hidden" name="programme_id" value={p.id}/><input name="code" placeholder="Code" required/><input name="name" placeholder="Name" required/><input type="date" name="start"/><input type="date" name="end"/><button className="btn">Create cohort</button></form></details>)}</section>;
}
