-- =====================================================================
-- 0006_registration.sql — participant self-registration with approval
-- =====================================================================
-- Apply after 0005, including on existing installations. Existing and
-- imported participants default to approved, so nothing about their flow
-- changes; only applicants arriving through /register wait for finance.
--
-- A pending registration is inert by construction, not by convention:
--   * the payments trigger refuses any write for an unapproved participant,
--     covering the public form, staff capture, payment batches and
--     resubmission, all of which write payments rows;
--   * issue_portal_otp() returns nothing for one, and the portal's reply is
--     unchanged, so the portal cannot be used to probe the register;
--   * the participant ID is generated by the sequence on insert, but only
--     reaches the applicant inside the approval email.

alter table participants add column registration_status text not null default 'approved';
alter table participants add constraint participants_registration_status_check
  check (registration_status in ('pending','approved','rejected'));
alter table participants add column registration_source text not null default 'registry';
alter table participants add constraint participants_registration_source_check
  check (registration_source in ('registry','import','self'));
-- The review note carries the rejection reason for staff; the reviewer
-- stamps record who decided and when.
alter table participants add column registration_note text;
alter table participants add column reviewed_by uuid references app_users(id) on delete set null;
alter table participants add column reviewed_at timestamptz;

-- The approval queue is this partial index: waiting rows, oldest first.
create index participants_pending_registration_idx on participants (created_at)
  where registration_status = 'pending';
-- One waiting self-registration per email address: a double submit (or a
-- race between two tabs) lands on this index as a 23505 instead of creating
-- two records to review. Approved, rejected and registry rows are unaffected.
create unique index participants_one_pending_self_idx on participants (email)
  where registration_status = 'pending' and registration_source = 'self';

-- The gate itself. Any payments write for a participant who is not approved
-- is refused, whoever the caller is — the service role included.
create or replace function enforce_approved_participant() returns trigger
language plpgsql as $$
begin
  if not exists (select 1 from participants
                  where id = new.participant_id
                    and registration_status = 'approved') then
    raise exception 'REGISTRATION_NOT_APPROVED' using errcode = 'P0001';
  end if;
  return new;
end $$;

create trigger payments_require_approved_participant
  before insert or update of participant_id on payments
  for each row execute function enforce_approved_participant();

-- Portal codes exist only for approved participants. Nothing about the
-- reply changes for anyone else, so the endpoint reveals nothing. The grant
-- stays service_role-only, as before.
create or replace function issue_portal_otp(p_participant_id uuid, p_code_hash text) returns uuid
language plpgsql security definer set search_path = public as $$
declare result uuid;
begin
  if auth.role() <> 'service_role' then raise exception 'FORBIDDEN'; end if;
  perform 1 from participants
    where id = p_participant_id and registration_status = 'approved'
    for update;
  if not found then return null; end if;
  if (select count(*) from portal_otps
       where participant_id = p_participant_id
         and created_at > now() - interval '1 hour') >= 5 then return null; end if;
  insert into portal_otps(participant_id, code_hash, expires_at)
  values(p_participant_id, p_code_hash, now() + interval '10 minutes')
  returning id into result;
  return result;
end $$;

-- Both decisions land in one transaction: the status change, the audit line
-- and the applicant's email commit together or not at all. Approval is the
-- first time the participant ID leaves the system. Rejection requires a
-- reason; it is kept on the row for staff and sent to the applicant.
create or replace function approve_registration(p_id uuid, p_actor uuid) returns void
language plpgsql security definer set search_path = public as $$
declare p participants%rowtype; v_email citext;
begin
  if p_actor is distinct from auth.uid()
     or not coalesce(current_role_of() in ('super_admin','finance_admin'), false) then
    raise exception 'FORBIDDEN';
  end if;
  select * into p from participants where id = p_id for update;
  if not found then raise exception 'PARTICIPANT_NOT_FOUND' using errcode = 'P0002'; end if;
  if p.registration_status <> 'pending' then raise exception 'ALREADY_REVIEWED'; end if;
  update participants
     set registration_status = 'approved', reviewed_by = p_actor, reviewed_at = now()
   where id = p_id;
  select email into v_email from app_users where id = p_actor;
  insert into audit_logs(actor_id, actor_email, action, entity_type, entity_id, summary)
  values(p_actor, v_email, 'registration.approved', 'participant', p_id::text,
         format('Self-registration approved for %s', p.full_name));
  insert into notifications(participant_id, template, recipient, payload)
  values(p_id, 'registration_approved', p.email,
         jsonb_build_object('name', p.first_name,
                            'participant_ref', p.participant_ref,
                            'programme', (select name from programmes where id = p.programme_id)));
end $$;

create or replace function reject_registration(p_id uuid, p_reason text, p_actor uuid) returns void
language plpgsql security definer set search_path = public as $$
declare p participants%rowtype; v_email citext;
begin
  if p_actor is distinct from auth.uid()
     or not coalesce(current_role_of() in ('super_admin','finance_admin'), false) then
    raise exception 'FORBIDDEN';
  end if;
  if coalesce(trim(p_reason), '') = '' then
    raise exception 'REJECTION_REASON_REQUIRED' using errcode = 'P0001';
  end if;
  select * into p from participants where id = p_id for update;
  if not found then raise exception 'PARTICIPANT_NOT_FOUND' using errcode = 'P0002'; end if;
  if p.registration_status <> 'pending' then raise exception 'ALREADY_REVIEWED'; end if;
  update participants
     set registration_status = 'rejected', registration_note = trim(p_reason),
         reviewed_by = p_actor, reviewed_at = now()
   where id = p_id;
  select email into v_email from app_users where id = p_actor;
  insert into audit_logs(actor_id, actor_email, action, entity_type, entity_id, summary, metadata)
  values(p_actor, v_email, 'registration.rejected', 'participant', p_id::text,
         format('Self-registration rejected for %s', p.full_name),
         jsonb_build_object('reason', trim(p_reason)));
  insert into notifications(participant_id, template, recipient, payload)
  values(p_id, 'registration_rejected', p.email,
         jsonb_build_object('name', p.first_name, 'reason', trim(p_reason)));
end $$;

revoke all on function approve_registration(uuid, uuid),
  reject_registration(uuid, text, uuid) from public, anon;
grant execute on function approve_registration(uuid, uuid),
  reject_registration(uuid, text, uuid) to authenticated;
